spring:
  application:
    name: ws-discovery-registry
  profiles:
    active: eureka-ha1

security:
  basic:
    enabled: true
  user:
    name: cwteam
    password: cwteam123456

---

server:
  port: 8761
spring:
  profiles: eureka-ha1
eureka:
  instance:
    hostname: eureka-ha1
    prefer-ip-address: false    # 使用IP通信，如果defaultZone使用域名形式注册，那该处必须为flase
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true    # 注册中心的高可用，需要开启下面两个参数，彼此互相注册
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cwteam:cwteam123456@eureka-ha2:8762/eureka/
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false   # 建议在生产环境开启

---

server:
  port: 8762
spring:
  profiles: eureka-ha2
eureka:
  instance:
    hostname: eureka-ha2
    prefer-ip-address: false    # 使用IP通信，如果defaultZone使用域名形式注册，那该处必须为flase
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true    # 注册中心的高可用，需要开启下面两个参数，彼此互相注册
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cwteam:cwteam123456@eureka-ha1:8761/eureka/
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false   # 建议在生产环境开启

